<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://www.saptco.com.sa" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/paymentTransactionBank/paymentTransactionBank/readPaymentTransactionFile"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/readPaymentTransactionFile.wsdl"/>
            <oracle-xsl-mapper:rootElement name="PaymentMessage" namespace="http://www.saptco.com.sa"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/readPaymentTransactionFile.wsdl"/>
            <oracle-xsl-mapper:rootElement name="PaymentMessage" namespace="http://www.saptco.com.sa"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [TUE FEB 16 02:24:24 EET 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:PaymentMessage>
         <ns0:PaymentTransaction>
            <ns0:CompanyCode>
               <xsl:value-of select="/ns0:PaymentMessage/ns0:PaymentTransaction/ns0:CompanyCode"/>
            </ns0:CompanyCode>
            <ns0:SequenceNum>
               <xsl:value-of select="/ns0:PaymentMessage/ns0:PaymentTransaction/ns0:SequenceNum"/>
            </ns0:SequenceNum>
            <ns0:TransactionData>
               <xsl:value-of select="/ns0:PaymentMessage/ns0:PaymentTransaction/ns0:TransactionData"/>
            </ns0:TransactionData>
            <ns0:TransactionComment>
               <xsl:value-of select="/ns0:PaymentMessage/ns0:PaymentTransaction/ns0:TransactionComment"/>
            </ns0:TransactionComment>
         </ns0:PaymentTransaction>
      </ns0:PaymentMessage>
   </xsl:template>
</xsl:stylesheet>
